#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install
sudo apt update
sudo apt-get install haproxy -y
echo -e "\nfrontend http
\tbind *:80
\tdefault_backend web-backend


backend web-backend
\tbalance roundrobin
\tserver web-01 52.207.52.20:80 check
\tserver web-02 54.90.18.27:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo service haproxy restart
