#!/usr/bin/env bash
# Configures a server to listen on port 80 for all active IPv4 IPs
echo "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     root /var/www/html;
     index index.html index.htm index.nginx-debian.html;
     server_name _;
     location / {
     	      try_files \${uri} \${uri}/ =404;
     }
}" | sudo tee /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -a /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
