#!/usr/bin/env bash
# Initialize counter

counter=1

# Loop until counter is equal to 10
while [ $counter -le 10 ]
do
    # Check if counter is at the 9th iteration
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    # Increment counter
    ((counter++))
done
