#!/usr/bin/env bash
# Initialize counter

counter=1

# Loop until counter is equal to 20
while [ $counter -le 20 ]
do
    # Display the current number
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    
    # Increment counter
    ((counter++))
done
