#!/usr/bin/env bash
# Script Name: change_ip.sh
# Description: This script changes the IP address resolution
# for localhost and facebook.com

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
