#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

chmod 644 /etc/nginx/nginx.conf
# Modify Nginx configuration to run as nginx user
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
